# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: "supervised_embeddings"
# - name: "SpacyNLP"
# - name: "SpacyTokenizer"
# - name: "SpacyFeaturizer"
#   return_sequence: true
# - name: "RegexFeaturizer"
#   return_sequence: true
# - name: "CRFEntityExtractor"
# - name: "EntitySynonymMapper"
# # - name: "SklearnIntentClassifier"
# - name: "EmbeddingIntentClassifier"
# #- name: "tensorflow_embedding_pipeline"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: AugmentedMemoizationPolicy
    max_history: 5
  # - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.85
    core_threshold: 0.85
    fallback_action_name: "action_custom_fallback"
